---
title: "p8105_hw1_jd3924.Rmd"
author: "Jiahe Deng"
date: "2022-09-24"
output: html_document
---
Question 1
```{r}
install.packages("palmerpenguins")
data("penguins", package = "palmerpenguins")
library(tidyverse)
penguins
```
```{r}
names(penguins)
nrow(penguins)
ncol(penguins)
mean(pull(penguins, flipper_length_mm), na.rm = TRUE)
```
In the penguins, there are 8 catagories, which are"species","island", "bill_length_mm",bill_depth_mm","flipper_length_mm","body_mass_g", "sex" and "year". There are 344 entries which mean 200.9152. 
```{r}
ggplot(data=penguins,aes(flipper_length_mm, bill_length_mm,color= species)) +
  geom_point()
```
```{r}
ggsave(file = "flipper vs. bill.jpg")
```

Question 2
```{r,echo=TRUE}
my_df <- 
  tibble(
    my_sample <- rnorm(10),
    vac_logical <- my_sample > 0,
    vac_char <- c("a","b","c","d","e","f","g","h","i","j"),
    var_factor <- factor(c("bad","bad","welldone","bad","good","welldone",
                           "good","welldone","good","bad"))
)
my_df